export const ADD_REMINDER = "[REMINDER] ADD REMINDER";
export const UPDATE_REMINDER = "[REMINDER] UPDATE REMINNDER";
export const REMOVE_REMINDER = "[REMINDER] REMOVE REMINDER";
export const GET_NOTIS = "[REMINDER] GET NOTIFICATIONS";
